FROM python:3.12-slim

RUN pip install --no-cache-dir prefect prefect[redis]

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

EXPOSE 4200